# NOTE: This PostgreSQL image is for a local development database only.

version: '3.8'

services:
  postgres:
    image: postgres:15.2
    container_name: umanage-db
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: umanagedb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data:
